GET http://localhost:3000/api/estudiantes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MGIzZjA0MjM5YWRiMjMzZDAxMzUyYTciLCJjb3JyZW8iOiJqb3NlbHVpc21vbnRlcm9AZ21haWwuY29tIiwiaWF0IjoxNjIyNjQ2MTYzLCJleHAiOjE2MjI2NDk3NjN9.wepM60xi1cyClJVbz4z7LISL3UQW2Vxs-bkj_Yde0tY

###
POST http://localhost:3000/api/estudiantes
Content-Type: application/json

{
    "nombre": "julian hernan",
    "correo": "julian@correo.com",
    "historial":{
        "procedencia": "Colegio Juan De Dios",
        "promedio": 80
    },
     "materias": {
        "nombre": "Matematica",
        "nota": 100,
        "comentario": "Muy participativo"
    }
   
}

###
PUT http://localhost:3000/api/estudiantes/60b25adccd6ef21d00399f5c
Content-Type: application/json

{
    "nombre":" luisana borjas",
    "correo":"luisanaa@gmail.com"
}

###
DELETE http://localhost:3000/api/estudiantes/60b25adccd6ef21d00399f5c


//-------------------- Materias
###
GET http://localhost:3000/api/materias/60b26920549c226a88d8f026

###
POST http://localhost:3000/api/materias/60b26920549c226a88d8f026
Content-Type: application/json

 {
        "nombre": "Fisica8",
        "nota": 10,
        "comentario": "necesita estudiar mas"
    }

###
DELETE  http://localhost:3000/api/materias/60b26920549c226a88d8f026/60b26ccd4fd0fb688c3dd1a5

###
PUT http://localhost:3000/api/materias/60b26920549c226a88d8f026/60b26920549c226a88d8f027
Content-Type:  application/json

{
    "nota":50,
    "comentario":"falto a clase muy seguido"
}
### 
POST http://localhost:3000/api/historial/id del estudiante
Content-Type: application/json

{
        "procedencia": "Colegio Juan De Dios",
        "promedio": 80
}
###
Delete http://localhost:3000/api/historial/id del estudiante/ id del historial que desea eliminar

###
PUT http://localhost:3000/api/historial/id del estudiante/ id del historial que desea Actualiza
Content-Type: application/json
{
   "procedencia": "Colegio Juan De Dios",
        "promedio": 30
}
}